<?php
namespace App\Models;
abstract class Faculty{
    const AGRICULTURE = "AGRICULTURE AND RELATED TECHNOLOGY";
    const ART = "ART, PRINTING AND RELATED TECHNOLOGY";
    const BUSINESS =    "BUSINESS, MANAGEMENT AND RELATED TECHNOLOGY";
    const ENGINEERING =   "ENGINEERING AND RELATED TECHNOLOGY";
    const ENVIRONMENTAL = "ENVIRONMENTAL DESIGN AND RELATED STUDIES";
    const FINANCE = "FINANCE AND RELATED STUDIES";
    const INFORMATION = "INFORMATION AND RELATED STUDIES";
    const HOSPITALITY = "HOSPITALITY AND RELATED TECHNOLOGY";
    const SCIENCE = "SCIENCE, COMPUTING AND RELATED TECHNOLOGY";
    const INSTITUTIONAL = "INSTITUTIONAL ADMIN";
    const HEALTH = "HEALTH AND RELATED TECHNOLOGY";
}